<script lang="ts">
  /**
   * SpaceBackdrop — the deep-space atmosphere behind the Home galaxy hero.
   *
   * Pure CSS: layered radial-gradient nebulas over a fixed starfield
   * generated by a single `box-shadow` multi-shadow (one shadow per star).
   * No canvas, no WebGL, no JS animation loop — keeps the Home shell light
   * (the heavy 3d-force-graph loads lazily, ON TOP of this, only when the
   * galaxy data arrives).
   *
   * Layers (bottom → top):
   *   1. `.space-void`       — the base cool-void background (token).
   *   2. `.space-nebula`     — 3 radial gradients, OKLCH: deep indigo,
   *                            plasma amber halo, faint teal aurora. Each
   *                            at low opacity so they stack as a single
   *                            atmosphere, not three colored blobs.
   *   3. `.space-stars--far` — small dim stars (high count, low opacity).
   *   4. `.space-stars--near`— larger brighter stars (low count, twinkle).
   *
   * The star box-shadow is generated at module load (deterministic via a
   * seeded PRNG so SSR/build output is stable — no hydration mismatch, no
   * flash of different stars between builds).
   *
   * Reduced motion: the twinkle animation collapses to `animation: none`
   * via the global @media (prefers-reduced-motion: reduce) rule in
   * app.css. Stars are still visible (static), only the breathing/twinkle
   * stops. WCAG 2.3.3 compliant.
   *
   * Performance: the box-shadow trick renders all stars in a single
   * composited layer (the browser treats multi-shadow box-shadow as one
   * paint). ~200 shadows cost ~0.1ms on a mid-range laptop. The nebulas
   * are static backgrounds (no filter animation), so they don't trigger
   * repaints. Total: cheaper than a single WebGL sprite.
   */
  function makeStars(count: number, maxSize: number, seed: number): string {
    // Mulberry32 — tiny deterministic PRNG. Same seed → same stars every
    // build. Avoids Math.random() which would change the bundle hash on
    // every build and break long-term caching.
    let s = seed >>> 0
    const rand = (): number => {
      s = (s + 0x6d2b79f5) >>> 0
      let t = s
      t = Math.imul(t ^ (t >>> 15), t | 1)
      t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296
    }
    const shadows: string[] = []
    for (let i = 0; i < count; i++) {
      // Tile within 100vw × 100vh (the viewport), not 200vw × 200vh.
      // The prior 200vw/200vh field put most stars off-screen at 1440px.
      const x = Math.round(rand() * 1000) / 10 // 0–100vw
      const y = Math.round(rand() * 1000) / 10 // 0–100vh
      const opacity = (0.45 + rand() * 0.55).toFixed(2) // 0.45–1.00 — brighter field
      // box-shadow's 3rd numeric arg (spread) grows (+) or shrinks (-) the
      // shadow. Base element is 1×1px; we want stars between 1px and
      // (1 + maxSize)px, so spread is in [0, maxSize]. Always positive,
      // never negative — avoids the `--0.03px` double-minus invalid CSS.
      const spread = (rand() * maxSize).toFixed(2)
      shadows.push(`${x}vw ${y}vh 0 ${spread}px rgba(255, 255, 255, ${opacity})`)
    }
    return shadows.join(', ')
  }

  // Two layers: far (small, many) + near (larger, fewer, twinkle).
  // Mobile counts drop via @media below — these are the desktop defaults.
  // 320 far stars at 100vw × 100vh ≈ 1 star per 4k px² at 1440×900 —
  // reads as a populated cosmic field (not snow). 80 near stars anchor
  // the depth illusion via size + twinkle.
  let farStars = makeStars(320, 1.0, 0x5f3759df)
  let nearStars = makeStars(80, 2.4, 0x82a5b34c)
</script>

<div class="space-backdrop" aria-hidden="true">
  <div class="space-void"></div>
  <div class="space-nebula"></div>
  <div class="space-stars space-stars--far" style="--star-shadows: {farStars}"></div>
  <div class="space-stars space-stars--near" style="--star-shadows: {nearStars}"></div>
</div>

<style>
  /* The backdrop is fixed to the viewport so it stays put as the hero
   * scrolls (Home is currently single-viewport, but this future-proofs
   * against a scroll-driven galaxy transition). z-index sits behind the
   * galaxy canvas, the overlay UI, and everything else. */
  .space-backdrop {
    position: fixed;
    inset: 0;
    z-index: 0;
    pointer-events: none;
    overflow: hidden;
  }

  .space-void {
    position: absolute;
    inset: 0;
    background: var(--surface-body);
  }

  /* Three nebula radial gradients. OKLCH keeps them perceptually uniform
   * across the void; low chroma + low alpha so they read as atmosphere,
   * not as colored shapes. Composed in a single background: declaration
   * so the browser paints them as one layer. */
  .space-nebula {
    position: absolute;
    inset: 0;
    background:
      radial-gradient(ellipse 80% 60% at 15% 20%,
        oklch(0.45 0.15 280 / 0.45) 0%,
        transparent 55%),
      radial-gradient(ellipse 60% 50% at 85% 75%,
        oklch(0.65 0.16 75 / 0.28) 0%,
        transparent 50%),
      radial-gradient(ellipse 70% 55% at 50% 50%,
        oklch(0.60 0.12 200 / 0.20) 0%,
        transparent 60%);
    /* Slow breathe — 24s loop, ease-in-out. Pauses under reduced-motion
     * via the global @media rule in app.css (animation-duration: 1ms). */
    animation: space-breathe 24s var(--ease-breathe) infinite;
    will-change: opacity;
  }

  @keyframes space-breathe {
    0%, 100% { opacity: 0.75; transform: scale(1); }
    50%      { opacity: 1;    transform: scale(1.03); }
  }

  /* Stars — a 1px white square with a massive multi-shadow box-shadow.
   * Each shadow is one star. The element itself never moves; the shadows
   * are positioned in viewport units so they tile across the screen. */
  .space-stars {
    position: absolute;
    top: 0;
    left: 0;
    width: 1px;
    height: 1px;
    background: transparent;
    /* var(--star-shadows) is set inline above with the generated string. */
    box-shadow: var(--star-shadows);
    border-radius: 50%;
  }

  .space-stars--far {
    /* Far stars don't twinkle — they're the stable field. */
    opacity: 0.6;
  }

  .space-stars--near {
    /* Near stars twinkle — staggered opacity pulse, 4s loop. */
    animation: space-twinkle 4s var(--ease-breathe) infinite;
  }

  @keyframes space-twinkle {
    0%, 100% { opacity: 0.85; }
    50%      { opacity: 0.4; }
  }

  /* Mobile: drop the star count by hiding the far layer entirely (the
   * near layer alone reads as a sparser field — still cosmos, less paint).
   * Keeps first paint cheap on phones. */
  @media (max-width: 48rem) {
    .space-stars--far {
      display: none;
    }
    .space-nebula {
      animation-duration: 36s;
    }
  }

  /* Reduced motion: kill the breathe + twinkle. Stars stay visible
   * (static), the nebula becomes a still gradient field. */
  @media (prefers-reduced-motion: reduce) {
    .space-nebula,
    .space-stars--near {
      animation: none;
    }
  }
</style>
